
const estadosCidades = {
        "SP": ["São Paulo","Guarulhos","Campinas","São Bernardo do Campo","Santo André","São José dos Campos","Sorocaba","Ribeirão Preto","Santos","Diadema","Jundiaí","Piracicaba","Carapicuíba","Osasco","Bauru","São José do Rio Preto","Mauá","Mogi das Cruzes","São Vicente","Itaquaquecetuba","Franca","Praia Grande","Taubaté","Limeira","Guarujá","Suzano","Taboão da Serra","Barueri","Cotia","Itapevi","Sumaré","Marília","Indaiatuba","Hortolândia","Presidente Prudente","São Carlos","Jacareí","Americana","Rio Claro","Araraquara","Santa Bárbara d'Oeste","Nova Odessa","São Caetano do Sul","Birigui","Itu","Botucatu","Franco da Rocha","Ferraz de Vasconcelos","Guaratinguetá","Ribeirão Pires","Tatuí","Votorantim","Poá","Lorena","Itapetininga","Valinhos","Araras","Pindamonhangaba","Cubatão","Lins","Atibaia","Catanduva","Ourinhos","Araçatuba","São João da Boa Vista","Ubatuba","São Roque","Caçapava","Avaré","Pirassununga","Mogi Guaçu","Lençóis Paulista","Várzea Paulista","Salto","Itapira","Itatiba","Assis","Jandira","Sertãozinho","Tupã","Matão","Barretos","Bebedouro","Jaboticabal","Adamantina","Bragança Paulista","Registro","Mococa","Caieiras","Olímpia","Vinhedo","Penápolis","Amparo","Embu das Artes","Itupeva","Bertioga","Mairiporã","Ilhabela"],
        "RJ" : ['Angra dos Reis','Araruama','Barra Mansa','Cabo Frio','Campos dos Goytacazes','Duque de Caxias','Itaboraí','Macaé','Magé','Maricá','Niterói','Nova Friburgo','Nova Iguaçu','Petrópolis','Rio de Janeiro','São Gonçalo','São João de Meriti','Saquarema','Teresópolis','Volta Redonda'],
        "RO" : ['Alta Floresta D\'Oeste','Alto Alegre dos Parecis','Alto Paraíso','Alvorada D\'Oeste','Ariquemes','Buritis','Cabixi','Cacaulândia','Cacoal','Campo Novo de Rondônia','Candeias do Jamari','Castanheiras','Cerejeiras','Chupinguaia','Colorado do Oeste','Corumbiara','Costa Marques','Cujubim','Espigão D\'Oeste','Governador Jorge Teixeira','Guajará-Mirim','Itapuã do Oeste','Jaru','Ji-Paraná','Machadinho D\'Oeste','Ministro Andreazza','Mirante da Serra','Monte Negro','Nova Brasilândia D\'Oeste','Nova Mamoré','Nova União','Novo Horizonte do Oeste','Ouro Preto do Oeste','Parecis','Pimenta Bueno','Pimenteiras do Oeste','Porto Velho','Presidente Médici','Primavera de Rondônia','Rio Crespo','Rolim de Moura','Santa Luzia D\'Oeste','São Felipe D\'Oeste','São Francisco do Guaporé','São Miguel do Guaporé','Seringueiras','Teixeirópolis','Theobroma','Urupá','Vale do Anari','Vale do Paraíso','Vilhena'],
        "AC" : ['Acrelândia','Assis Brasil','Brasiléia','Bujari','Capixaba','Cruzeiro do Sul','Epitaciolândia','Feijó','Jordão','Mâncio Lima','Manoel Urbano','Marechal Thaumaturgo','Plácido de Castro','Porto Acre','Porto Walter','Rio Branco','Rodrigues Alves','Santa Rosa do Purus','Sena Madureira','Senador Guiomard','Tarauacá','Xapuri'],
        "AM" : ["Manaus","Parintins","Itacoatiara","Manacapuru","Coari","Tefé","Tabatinga","Maués","Manicoré","Humaitá","Iranduba","Lábrea","São Gabriel da Cachoeira","Benjamin Constant","Borba","Autazes","Nova Olinda do Norte","São Paulo de Olivença","Careiro da Várzea","Presidente Figueiredo","Rio Preto da Eva","Nhamundá","Santa Isabel do Rio Negro","Barreirinha","Santo Antônio do Içá","Apuí","Amaturá","Anori","Barcelos","Novo Airão"],
        "RR" : ['Alto Alegre','Amajari','Boa Vista','Bonfim','Cantá','Caracaraí','Caroebe','Iracema','Mucajaí','Normandia','Pacaraima','Rorainópolis','São João da Baliza','São Luiz','Uiramutã'],
        "PA": ['Abaetetuba', 'Abel Figueiredo', 'Acará', 'Afuá', 'Água Azul do Norte', 'Alenquer', 'Almeirim','Altamira', 'Anajás', 'Ananindeua', 'Anapu', 'Augusto Corrêa', 'Aurora do Pará', 'Aveiro','Bagre', 'Baião', 'Bannach', 'Barcarena', 'Belém', 'Belterra', 'Benevides', 'Bom Jesus do Tocantins','Bonito', 'Bragança', 'Brasil Novo', 'Brejo Grande do Araguaia', 'Breu Branco', 'Breves','Bujaru', 'Cachoeira do Arari', 'Cachoeira do Piriá', 'Cametá', 'Canaã dos Carajás','Capanema', 'Capitão Poço', 'Castanhal', 'Chaves', 'Colares', 'Conceição do Araguaia','Concórdia do Pará', 'Cumaru do Norte', 'Curionópolis', 'Curralinho', 'Curuá', 'Curuçá','Dom Eliseu', 'Eldorado dos Carajás', 'Faro', 'Floresta do Araguaia', 'Garrafão do Norte','Goianésia do Pará', 'Gurupá', 'Igarapé-Açu', 'Igarapé-Miri', 'Inhangapi', 'Ipixuna do Pará','Irituia', 'Itaituba', 'Itupiranga', 'Jacareacanga', 'Jacundá', 'Juruti', 'Limoeiro do Ajuru','Mãe do Rio', 'Magalhães Barata', 'Marabá', 'Maracanã', 'Marapanim', 'Marituba','Medicilândia', 'Melgaço', 'Mocajuba', 'Moju', 'Mojuí dos Campos', 'Monte Alegre','Muaná', 'Nova Esperança do Piriá', 'Nova Ipixuna', 'Nova Timboteua', 'Novo Progresso','Novo Repartimento', 'Óbidos', 'Oeiras do Pará', 'Oriximiná', 'Ourém', 'Ourilândia do Norte','Pacajá', 'Palestina do Pará', 'Paragominas', 'Parauapebas', 'Pau D\'Arco', 'Peixe-Boi','Piçarra', 'Placas', 'Ponta de Pedras', 'Portel', 'Porto de Moz', 'Prainha', 'Primavera','Quatipuru', 'Redenção', 'Rio Maria', 'Rondon do Pará', 'Rurópolis', 'Salinópolis','Salvaterra', 'Santa Bárbara do Pará', 'Santa Cruz do Arari', 'Santa Izabel do Pará','Santa Luzia do Pará', 'Santa Maria das Barreiras', 'Santa Maria do Pará', 'Santana do Araguaia'],
        "AP" : ['Santana','Macapá','Mazagão','Oiapoque','Pedra Branca do Amapari','Calçoene','Amapá','Pracuúba','Porto Grande','Ferreira Gomes','Cutias','Tartarugalzinho','Vitória do Jari','Itaubal','Serra do Navio'],
        "TO" : ['Abreulândia', 'Aguiarnópolis', 'Aliança do Tocantins', 'Almas', 'Alvorada', 'Ananás', 'Angico', 'Aparecida do Rio Negro', 'Aragominas', 'Araguacema', 'Araguaçu', 'Araguaína', 'Araguanã', 'Araguatins', 'Arapoema', 'Arraias', 'Augustinópolis', 'Aurora do Tocantins', 'Axixá do Tocantins', 'Babaçulândia', 'Bandeirantes do Tocantins', 'Barra do Ouro', 'Barrolândia', 'Bernardo Sayão', 'Bom Jesus do Tocantins', 'Brasilândia do Tocantins', 'Brejinho de Nazaré', 'Buriti do Tocantins', 'Cachoeirinha', 'Campos Lindos', 'Cariri do Tocantins', 'Carmolândia', 'Carrasco Bonito', 'Caseara', 'Centenário', 'Chapada da Natividade', 'Chapada de Areia', 'Colinas do Tocantins', 'Colméia', 'Combinado', 'Conceição do Tocantins', 'Couto Magalhães', 'Cristalândia', 'Crixás do Tocantins', 'Darcinópolis', 'Dianópolis', 'Divinópolis do Tocantins', 'Dois Irmãos do Tocantins', 'Dueré', 'Esperantina', 'Fátima', 'Figueirópolis', 'Filadélfia', 'Formoso do Araguaia', 'Fortaleza do Tabocão', 'Goianorte', 'Goiatins', 'Guaraí', 'Gurupi', 'Ipueiras', 'Itacajá', 'Itaguatins', 'Itapiratins', 'Itaporã do Tocantins', 'Jaú do Tocantins', 'Juarina', 'Lagoa da Confusão', 'Lagoa do Tocantins', 'Lajeado', 'Lavandeira', 'Lizarda', 'Luzinópolis', 'Marianópolis do Tocantins', 'Mateiros', 'Maurilândia do Tocantins', 'Miracema do Tocantins', 'Miranorte', 'Monte do Carmo', 'Monte Santo do Tocantins', 'Muricilândia', 'Natividade', 'Nazaré', 'Nova Olinda', 'Nova Rosalândia', 'Novo Acordo', 'Novo Alegre', 'Novo Jardim', 'Oliveira de Fátima', 'Palmeirante', 'Palmeiras do Tocantins', 'Palmeirópolis', 'Paraíso do Tocantins', 'Paranã', 'Pau D`Arco', 'Pedro Afonso', 'Peixe', 'Pequizeiro', 'Pindorama do Tocantins', 'Piraquê', 'Pium', 'Ponte Alta do Bom Jesus'],
        "MA": ["Açailândia","Afonso Cunha","Água Doce do Maranhão","Alcântara","Aldeias Altas","Altamira do Maranhão","Alto Alegre do Maranhão","Alto Alegre do Pindaré","Alto Parnaíba","Amapá do Maranhão","Amarante do Maranhão","Anajatuba","Anapurus","Apicum-Açu","Araguanã","Araioses","Arame","Arari","Axixá","Bacabal","Bacabeira","Bacuri","Bacurituba","Balsas","Barão de Grajaú","Barra do Corda","Barreirinhas","Bela Vista do Maranhão","Belágua","Benedito Leite","Bequimão","Bernardo do Mearim","Boa Vista do Gurupi","Bom Jardim","Bom Jesus das Selvas","Bom Lugar","Brejo","Brejo de Areia","Buriti","Buriti Bravo","Buriticupu","Buritirana","Cachoeira Grande","Cajapió","Cajari","Campestre do Maranhão","Cândido Mendes","Cantanhede","Capinzal do Norte","Carolina","Carutapera","Caxias","Cedral","Central do Maranhão","Centro do Guilherme","Centro Novo do Maranhão","Chapadinha","Cidelândia","Codó","Coelho Neto","Colinas","Conceição do Lago-Açu","Coroatá","Cururupu","Davinópolis","Dom Pedro","Duque Bacelar","Esperantinópolis","Estreito","Feira Nova do Maranhão","Fernando Falcão","Formosa da Serra Negra","Fortaleza dos Nogueiras","Fortuna","Godofredo Viana","Gonçalves Dias","Governador Archer","Governador Edison Lobão","Governador Eugênio Barros","Governador Luiz Rocha","Governador Newton Bello","Governador Nunes Freire","Graça Aranha","Grajaú","Guimarães","Humberto de Campos","Icatu","Igarapé do Meio","Igarapé Grande","Imperatriz","Itaipava do Grajaú","Itapecuru Mirim"],
        "PI" : ['Acauã','Agricolândia','Água Branca','Alagoinha do Piauí','Alegrete do Piauí','Alto Longá','Altos','Alvorada do Gurguéia','Amarante','Angical do Piauí','Anísio de Abreu','Antônio Almeida','Aroazes','Aroeiras do Itaim','Arraial','Assunção do Piauí','Avelino Lopes','Baixa Grande do Ribeiro','Barra D\'Alcântara','Barras','Barreiras do Piauí','Barro Duro','Batalha','Bela Vista do Piauí','Belém do Piauí','Beneditinos','Bertolínia','Betânia do Piauí','Boa Hora','Bocaina','Bom Jesus','Bom Princípio do Piauí','Bonfim do Piauí','Boqueirão do Piauí','Brasileira','Brejo do Piauí','Buriti dos Lopes','Buriti dos Montes','Cabeceiras do Piauí','Cajazeiras do Piauí','Cajueiro da Praia','Caldeirão Grande do Piauí','Campinas do Piauí','Campo Alegre do Fidalgo','Campo Grande do Piauí','Campo Largo do Piauí','Campo Maior','Canavieira','Canto do Buriti','Capitão de Campos','Capitão Gervásio Oliveira','Caracol','Caraúbas do Piauí','Caridade do Piauí','Castelo do Piauí','Caxingó','Cocal','Cocal de Telha','Cocal dos Alves','Coivaras','Colônia do Gurguéia','Colônia do Piauí','Conceição do Canindé','Coronel José Dias','Corrente','Cristalândia do Piauí','Cristino Castro','Curimatá','Currais','Curral Novo do Piauí','Curralinhos','Demerval Lobão','Dirceu Arcoverde','Dom Expedito Lopes','Dom Inocêncio','Domingos Mourão','Elesbão Veloso','Eliseu Martins','Esperantina','Fartura do Piauí','Flores do Piauí','Floresta do Piauí','Floriano','Francinópolis','Francisco Ayres','Francisco Macedo','Francisco Santos','Fronteiras'],
        "CE": ["Fortaleza","Caucaia","Juazeiro do Norte","Maracanaú","Sobral","Crato","Itapipoca","Maranguape","Iguatu","Quixadá","Canindé","Pacajus","Crateús","Aquiraz","Pacatuba","Camocim","Quixeramobim","Russas","Aracati","Tianguá","Limoeiro do Norte","Barbalha","Parambu","Cascavel","Beberibe","Acaraú","Horizonte","Viçosa do Ceará","Morada Nova","Guaiúba",],
        "RN": ["Natal","Mossoró","Parnamirim","São Gonçalo do Amarante","Macaíba","Ceará-Mirim","Caicó","Assu","Currais Novos","São José de Mipibu","João Câmara","Santa Cruz","Apodi","Jucurutu","Canguaretama","Touros","Pau dos Ferros","Extremoz","Baraúna","Nísia Floresta","Goianinha","São Miguel","Angicos","Ipanguaçu","São Paulo do Potengi","Umarizal","Areia Branca","Patu","Poço Branco","Taipu","São Tomé","Serra do Mel","São Bento do Norte","Serra Negra do Norte","Carnaubais","Serra de São Bento","Campo Grande","Rio do Fogo","Guamaré","Maxaranguape","Caraúbas","Monte Alegre"],
        "PB" : ['Água Branca','Aguiar','Alagoa Grande','Alagoa Nova','Alagoinha','Alcantil','Algodão de Jandaíra','Alhandra','Amparo','Aparecida','Araçagi','Arara','Araruna','Areia','Areia de Baraúnas','Areial','Aroeiras','Assunção','Baía da Traição','Bananeiras','Baraúna','Barra de Santa Rosa','Barra de Santana','Barra de São Miguel','Bayeux','Belém','Belém do Brejo do Cruz','Bernardino Batista','Boa Ventura','Boa Vista','Bom Jesus','Bom Sucesso','Bonito de Santa Fé','Boqueirão','Borborema','Brejo do Cruz','Brejo dos Santos','Caaporã','Cabaceiras','Cabedelo','Cachoeira dos Índios','Cacimba de Areia','Cacimba de Dentro','Cacimbas','Caiçara','Cajazeiras','Cajazeirinhas','Caldas Brandão','Camalaú','Campina Grande','Campo de Santana','Capim','Caraúbas','Carrapateira','Casserengue','Catingueira','Catolé do Rocha','Caturité','Conceição','Condado','Conde','Congo','Coremas','Coxixola','Cruz do Espírito Santo','Cubati','Cuité','Cuité de Mamanguape','Cuitegi','Curral de Cima','Curral Velho','Damião','Desterro','Diamante','Dona Inês','Duas Estradas','Emas','Esperança','Fagundes','Frei Martinho','Gado Bravo','Guarabira','Gurinhém','Gurjão','Ibiara','Igaracy','Imaculada','Ingá','Itabaiana','Itaporanga','Itapororoca','Itatuba','Jacaraú','Jericó','João Pessoa','Joca Claudino','Juarez Távora','Juazeirinho','Junco do Seridó','Juripiranga','Juru','Lagoa','Lagoa de Dentro','Lagoa Seca','Lastro','Livramento','Logradouro'],
        "PE": ["Recife","Jaboatão dos Guararapes","Olinda","Caruaru","Petrolina","Paulista","Cabo de Santo Agostinho","Camaragibe","Garanhuns","Vitória de Santo Antão","Igarassu","São Lourenço da Mata","Santa Cruz do Capibaribe","Abreu e Lima","Ipojuca","Serra Talhada","Araripina","Gravatá","Carpina","Goiana","Belo Jardim","Arcoverde","Ouricuri","Escada","Pesqueira","Surubim","Palmares","Bezerros","Salgueiro","Limoeiro","Afogados da Ingazeira","Petrolândia","Timbaúba","Paudalho","Catende","Ferreiros","Moreno","São Joaquim do Monte","São José da Coroa Grande","Barreiros","Itambé","Lajedo","Glória do Goitá"],
        "AL" : ["Água Branca","Anadia","Arapiraca","Atalaia","Barra de Santo Antônio","Barra de São Miguel","Batalha","Belém","Belo Monte","Boca da Mata","Branquinha","Cacimbinhas","Cajueiro","Campestre","Campo Alegre","Campo Grande","Canapi","Capela","Carneiros","Chã Preta","Coité do Nóia","Colônia Leopoldina","Coqueiro Seco","Coruripe","Craíbas","Delmiro Gouveia","Dois Riachos","Estrela de Alagoas","Feira Grande","Feliz Deserto","Flexeiras","Girau do Ponciano","Ibateguara","Igaci","Igreja Nova","Inhapi","Jacaré dos Homens","Jacuípe","Japaratinga","Jaramataia","Jequiá da Praia","Joaquim Gomes","Jundiá","Junqueiro","Lagoa da Canoa","Limoeiro de Anadia","Maceió","Major Isidoro","Maragogi","Maravilha","Marechal Deodoro","Maribondo","Mar Vermelho","Mata Grande","Matriz de Camaragibe","Messias","Minador do Negrão","Monteirópolis","Murici","Novo Lino","Olho d'Água das Flores","Olho d'Água do Casado","Olho d'Água Grande","Olivença","Ouro Branco","Palestina","Palmeira dos Índios","Pão de Açúcar","Pariconha","Paripueira","Passo de Camaragibe","Paulo Jacinto","Penedo","Piaçabuçu","Pilar","Pindoba","Piranhas","Poço das Trincheiras","Porto Calvo","Porto de Pedras","Porto Real do Colégio","Quebrangulo","Rio Largo","Roteiro","Santa Luzia do Norte","Santana do Ipanema","Santana do Mundaú","São Brás","São José da Laje","São José da Tapera","São Luís do Quitunde","São Miguel dos Campos","São Miguel dos Milagres","São Sebastião","Satuba","Senador Rui Palmeira","Tanque d'Arca"],
        "SE": ["Amparo de São Francisco","Aquidabã","Aracaju","Arauá","Areia Branca","Barra dos Coqueiros","Boquim","Brejo Grande","Campo do Brito","Canhoba","Canindé de São Francisco","Capela","Carira","Carmópolis","Cedro de São João","Cristinápolis","Cumbe","Divina Pastora","Estância","Feira Nova","Frei Paulo","Gararu","General Maynard","Gracho Cardoso","Ilha das Flores","Indiaroba","Itabaiana","Itabaianinha","Itabi","Itaporanga d'Ajuda","Japaratuba","Japoatã","Lagarto","Laranjeiras","Macambira","Malhada dos Bois","Malhador","Maruim","Moita Bonita","Monte Alegre de Sergipe","Muribeca","Neópolis","Nossa Senhora Aparecida","Nossa Senhora da Glória","Nossa Senhora das Dores","Nossa Senhora de Lourdes","Nossa Senhora do Socorro","Pacatuba","Pedra Mole","Pedrinhas","Pinhão","Pirambu","Poço Redondo","Poço Verde","Porto da Folha","Propriá","Riachão do Dantas","Riachuelo","Ribeirópolis","Rosário do Catete","Salgado","Santa Luzia do Itanhy","Santa Rosa de Lima","Santana do São Francisco","Santo Amaro das Brotas","São Cristóvão","São Domingos","São Francisco","São Miguel do Aleixo","Simão Dias","Siriri","Telha","Tobias Barreto","Tomar do Geru","Umbaúba"],
        "BA": ["Abaíra", "Abaré", "Acajutiba", "Adustina", "Água Fria", "Aiquara", "Alagoinhas", "Alcobaça", "Almadina", "Amargosa","Amélia Rodrigues", "América Dourada", "Anagé", "Andaraí", "Andorinha", "Angical", "Anguera", "Antas", "Antônio Cardoso","Antônio Gonçalves", "Aporá", "Apuarema", "Araças", "Aracatu", "Araci", "Aramari", "Arataca", "Aratuípe", "Aurelino Leal","Baianópolis", "Baixa Grande", "Banzaê", "Barra", "Barra da Estiva", "Barra do Choça", "Barra do Mendes", "Barra do Rocha","Barreiras", "Barro Alto", "Barro Preto", "Barrocas", "Belmonte", "Belo Campo", "Biritinga", "Boa Nova", "Boa Vista do Tupim","Bom Jesus da Lapa", "Bom Jesus da Serra", "Boninal", "Bonito", "Boquira", "Botuporã", "Brejões", "Brejolândia", "Brotas de Macaúbas","Brumado", "Buerarema", "Buritirama", "Caatiba", "Cabaceiras do Paraguaçu", "Cachoeira", "Caculé", "Caém", "Caetanos","Caetité", "Cafarnaum", "Cairu", "Caldeirão Grande", "Camacan", "Camaçari", "Camamu", "Campo Alegre de Lourdes", "Campo Formoso","Canápolis", "Canarana", "Canavieiras", "Candeal", "Candeias", "Candiba", "Cândido Sales", "Cansanção", "Canudos","Capela do Alto Alegre", "Capim Grosso", "Caraíbas", "Caravelas", "Cardeal da Silva", "Carinhanha", "Casa Nova", "Castro Alves","Catolândia", "Catu", "Caturama", "Central", "Chorrochó", "Cícero Dantas", "Cipó", "Coaraci", "Cocos", "Conceição da Feira","Conceição do Almeida", "Conceição do Coité", "Conceição do Jacuípe", "Conde", "Condeúba", "Contendas do Sincorá", "Coração de Maria","Cordeiros", "Coribe", "Coronel João Sá", "Correntina", "Cotegipe", "Cravolândia", "Crisópolis", "Cristópolis", "Cruz das Almas","Curaçá", "Dário Meira", "Dias d'Ávila", "Dom Basílio", "Dom Macedo Costa"],
        "MG" : ["Abadia dos Dourados","Abaeté","Abre Campo","Acaiaca","Açucena","Volta Grande","Wenceslau Braz","Água Boa","Água Comprida"],
        "ES" : ["Afonso Cláudio","Água Doce do Norte","Águia Branca","Alegre","Alfredo Chaves","Alto Rio Novo","Anchieta","Apiacá","Aracruz","Atilio Vivacqua","Baixo Guandu","Barra de São Francisco","Boa Esperança","Bom Jesus do Norte","Brejetuba","Cachoeiro de Itapemirim","Cariacica","Castelo","Colatina","Conceição da Barra","Conceição do Castelo","Divino de São Lourenço","Domingos Martins","Dores do Rio Preto","Ecoporanga","Fundão","Governador Lindenberg","Guaçuí","Guarapari","Ibatiba","Ibiraçu","Ibitirama","Iconha","Irupi","Itaguaçu","Itapemirim","Itarana","Iúna","Jaguaré","Jerônimo Monteiro","João Neiva","Laranja da Terra","Linhares","Mantenópolis","Marataízes","Marechal Floriano","Marilândia","Mimoso do Sul","Montanha","Mucurici","Muniz Freire","Muqui","Nova Venécia","Pancas","Pedro Canário","Pinheiros","Piúma","Ponto Belo","Presidente Kennedy","Rio Bananal","Rio Novo do Sul","Santa Leopoldina","Santa Maria de Jetibá","Santa Teresa","São Domingos do Norte","São Gabriel da Palha","São José do Calçado","São Mateus","São Roque do Canaã","Serra","Sooretama","Vargem Alta","Venda Nova do Imigrante","Viana","Vila Pavão","Vila Valério","Vila Velha","Vitória"],
        "PR" : ["Curitiba","Londrina","Maringá","Ponta Grossa","Cascavel","São José dos Pinhais","Foz do Iguaçu","Colombo","Guarapuava","Paranaguá",],
        "SC" : ["Florianópolis","Joinville","Blumenau","São José","Chapecó","Criciúma"],
        "RS": ["Porto Alegre","Caxias do Sul","Pelotas","Canoas","Santa Maria","Gravataí","Viamão","Novo Hamburgo","São Leopoldo","Rio Grande","Alvorada","Passo Fundo","Sapucaia do Sul","Uruguaiana","Santa Cruz do Sul","Cachoeirinha","Bagé","Bento Gonçalves","Erechim","Guaíba"],
        "MS" : ["Água Clara","Alcinópolis","Amambai","Anastácio","Anaurilândia","Angélica","Antônio João","Aparecida do Taboado","Aquidauana","Aral Moreira","Bandeirantes","Bataguassu","Batayporã","Bela Vista","Bodoquena","Bonito","Brasilândia","Caarapó","Camapuã","Campo Grande","Caracol","Cassilândia","Chapadão do Sul","Corguinho","Coronel Sapucaia","Corumbá","Costa Rica","Coxim","Deodápolis","Dois Irmãos do Buriti","Douradina","Dourados","Eldorado","Fátima do Sul","Figueirão","Glória de Dourados","Guia Lopes da Laguna","Iguatemi","Inocência","Itaporã","Itaquiraí","Ivinhema","Japorã","Jaraguari","Jardim","Jateí","Juti","Ladário","Laguna Carapã","Maracaju","Miranda","Mundo Novo","Naviraí","Nioaque","Nova Alvorada do Sul","Nova Andradina","Novo Horizonte do Sul","Paranaíba","Paranhos","Pedro Gomes","Ponta Porã","Porto Murtinho","Ribas do Rio Pardo","Rio Brilhante","Rio Negro","Rio Verde de Mato Grosso","Rochedo","Santa Rita do Pardo","São Gabriel do Oeste","Selvíria","Sete Quedas","Sidrolândia","Sonora","Tacuru","Taquarussu","Terenos","Três Lagoas","Vicentina"],
        "MT" : ["Água Boa","Alta Floresta","Alto Araguaia","Alto Boa Vista","Alto Garças"],
        "GO" : ["Abadia de Goiás","Abadiânia","Acreúna","Adelândia","Água Fria de Goiás","Vianópolis","Vicentinópolis","Vila Boa","Vila Propício"],
        "DF" : ["Brasília", "Ceilândia", "Taguatinga", "Planaltina", "Samambaia", "Recanto das Emas", "Águas Claras", "Gama", "Santa Maria", "Sobradinho", "Itapoã", "Paranoá", "Guará", "Cruzeiro", "Lago Sul", "Riacho Fundo", "Lago Norte", "Candangolândia", "Núcleo Bandeirante", "Park Way", "SIA", "SCIA", "Sudoeste/Octogonal", "Varjão", "Brazlândia", "Sobradinho II", "Jardim Botânico", "Fercal", "Vicente Pires", "Vale do Amanhecer", "Lago Oeste", "Jardins Mangueiral", "Solar de Brasília", "Setor de Indústria e Abastecimento", "Setor Habitacional Vicente Pires", "Vila Planalto", "Setor de Hotéis e Turismo Norte", "Setor Complementar de Indústria e Abastecimento", "Setor de Indústrias Gráficas", "Setor Hoteleiro de Taguatinga", "Setor Hoteleiro Sul", "Setor Hoteleiro Norte", "Setor Bancário Sul", "Setor Bancário Norte", "Setor Sudoeste", "Setor Noroeste", "Setor de Habitações Individuais Norte", "Setor de Habitações Individuais Sul", "Setor de Habitações Coletivas Norte", "Setor de Habitações Coletivas Sul", "Setor de Oficinas Sul", "Setor de Oficinas Norte", "Setor de Autarquias Sul", "Setor de Autarquias Norte", "Setor Cultural Norte", "Setor Cultural Sul", "Setor Comercial Sul", "Setor Comercial Norte", "Setor de Clubes Esportivos Sul", "Setor de Clubes Esportivos Norte", "Setor de Clubes Sul", "Setor de Clubes Norte", "Setor de Administração Municipal Sul", "Setor de Administração Municipal Norte", "Setor Hospitalar Local Sul", "Setor Hospitalar Local Norte", "Setor Militar Urbano", "Setor Militar Urbano de Taguatinga"]
    };

const apiKey = '9eff6d3d63b7c7be8e54d33d30584705';

$(document).ready(function () {
    // Inicializa o Select2
    $('#estado, #cidade').select2({
        theme: 'bootstrap4'
    });

    // Preenche o select de estados com os estados do Brasil
    for (const estado in estadosCidades) {
        $('#estado').append(new Option(estado, estado));
    }

    // Atualiza o select de cidades com base no estado selecionado
    $('#estado').on('change', function () {
        const estadoSelecionado = $(this).val();
        const cidades = estadosCidades[estadoSelecionado] || [];

        $('#cidade').empty();
        for (const cidade of cidades) {
            $('#cidade').append(new Option(cidade, cidade));
        }
    });

    // Busca e exibe o clima ao selecionar uma cidade
    $('#cidade').on('change', function () {
        const cidadeSelecionada = $(this).val();

        if (cidadeSelecionada) {
            buscaClima(cidadeSelecionada);
        } else {
            $('#resultado').empty();
        }
    });
});

function buscaClima(cidade) {
    const apiUrl = `https://api.openweathermap.org/data/2.5/weather?q=${cidade},BR&appid=${apiKey}&units=metric&lang=pt_br`;

    $.getJSON(apiUrl, function (data) {
        const temperatura = data.main.temp.toFixed(1);
        const descricao = data.weather[0].description;
        const umidade = data.main.humidity;

        const resultadoHtml = `
            <h4>Clima em ${cidade}:</h4>
            <p>Temperatura: ${temperatura}°C</p>
            <p>Descrição: ${descricao}</p>
            <p>Umidade: ${umidade}%</p>
        `;

        $('#resultado').html(resultadoHtml);
    }).fail(function () {
        alert('Erro ao buscar informações de clima. Por favor, tente novamente.');
    });
}